## gitea に同期する用の actions
name: main

on:
  workflow_dispatch:
    push:
        branches:
        - "main"
  push:
    branches:
      - 'master'

env:
  GITEA_SSH_URL: 'ssh://git@git.trap.jp:2200/22hac07win/route-server.git'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set config
        run: |
          echo "${{ secrets.GITEA_SECRET }}" > ~/deploy_key
          chmod 600 ~/deploy_key
          git config --local user.email "github@actions"
          git config --local user.name "github"
      - name: Push changes
        env:
          GIT_SSH_COMMAND: ssh -i ~/deploy_key -o StrictHostKeyChecking=no -F /dev/null
        run: |
          git fetch --unshallow origin
          git push -f ${{ env.GITEA_SSH_URL }}